---
booktitle: Proceedings of the third International Workshop on Machine Learning in
  Systems Biology
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
publisher: PMLR
volume: 8
year: '2009'
start: 2009-09-05
end: 2009-09-06
published: 2009-03-02
shortname: MLSB 2009
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: DzeroskiMLSB2009
month: 0
cycles: false
editor:
- given: Sašo
  family: Džeroski
- given: Pierre
  family: Guerts
- given: Juho
  family: Rousu
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the third International Workshop on Machine Learning in Systems Biology
    Held in Ljubljana, Slovenia on 05-06 September 2009

  Published as Volume 8 by the Proceedings of Machine Learning Research on 02 March 2009.

  Volume Edited by:
    Sašo Džeroski
    Pierre Guerts
    Juho Rousu

  Series Editors:
    Neil D. Lawrence
date_str: 05--06 Sep
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v8"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
permalink: "/:title.html"
ghub:
  edit: true
  repository: v8
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Machine Learning in Systems Biology
  url: http://mlsb09.ijs.si/
  location: Ljubljana, Slovenia
  dates:
  - 2009-09-05
  - 2009-09-06
  number: 3
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
